### ISSUE TITLE
Filter through dish list

### ISSUE THREAD

**Issue by renandres** [dholde/BestFoodApp#45]
User story: As a user I want to filter through my inital dish-list, in order to find the best dish for me. Filter criteria: price, # of portions, description...

Criteria:/

Data: /

Screens:
![search](https://user-images.githubusercontent.com/24482175/27338820-7503aedc-55d6-11e7-99d4-f7014e7baddc.PNG)

**Comment by jbaumont** [comment]
Price, Type of dish, Distance from me, Number of portion

**Comment by jbaumont** [comment]
--> See Issue 14 "Sort dishes (landing page)"
